[package]
name = "etcd_registservice"
version = "0.1.0"
authors = ["Armer Song <armer_song@qq.com>"]
edition = "2018"

[dependencies]
etcd="0.9"
futures="0.1"
tokio="0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
